"""Added user info

Revision ID: a43a303bc9a6
Revises: 10a8b1ff70c9
Create Date: 2024-03-01 00:19:10.702835

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a43a303bc9a6'
down_revision: Union[str, None] = '10a8b1ff70c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_date')
    op.drop_column('users', 'registration_date')
    # ### end Alembic commands ###
