version: '3.0'
services:
  db:
    image: postgres:15
    container_name: clinic_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clinic_db
    ports:
      - 5432:5432
